name: publish

on:
  pull_request:
    branches: ["main"]

jobs:
  publish-to-site:
    name: Publish the document to the site
    runs-on: ubuntu-latest
    env:
      FTP_SERVER: ${{ secrets.FTP_SERVER }}
      FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
      FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      FTP_SERVER_DIR: ${{ secrets.FTP_SERVER_DIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      