name: publish

on:
  pull_request:
    branches: ["main"]
    # types: [closed]

jobs:
  publish-to-site:
    name: Publish the document to the site
    runs-on: ubuntu-latest
    env:
      RCLONE_CONFIG_FTP_TYPE: ftp
      RCLONE_CONFIG_FTP_HOST: ${{ secrets.FTP_SERVER }}
      RCLONE_CONFIG_FTP_USER: ${{ secrets.FTP_USERNAME }}
      RCLONE_CONFIG_FTP_PASS: ${{ secrets.FTP_PASSWORD }}
      RCLONE_CONFIG_FTP_TLS: false
      RCLONE_CONFIG_FTP_EXPLICIT_TLS: false
      FTP_SERVER_DIR: ${{ secrets.FTP_SERVER_DIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Upload files to the site
        run: |
          sudo -v ; curl https://rclone.org/install.sh | sudo bash
          rclone sync ./ ftp:${FTP_SERVER_DIR} --exclude="/.git**" -v --dry-run